
import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextProps {
  language: string;
  setLanguage: (language: string) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === 'en' ? 'ar' : 'en');
  };

  const translations = {
    en: {
      dashboard: 'Dashboard',
      vehicles: 'Vehicles',
      bookings: 'Bookings',
      customers: 'Customers',
      settings: 'Settings',
      archivedVehicles: 'Archived Vehicles',
      logout: 'Logout',
      language: 'Language',
      branch: 'Branch',
      allBranches: 'All Branches',
      totalActiveVehicles: 'Total Active Vehicles',
      availableVehicles: 'Available Vehicles',
      activeBookings: 'Active Bookings',
      totalRevenue: 'Total Revenue',
      vehicleStatus: 'Vehicle Status',
      revenueOverview: 'Revenue Overview',
      recentBookings: 'Recent Bookings',
      allStatuses: 'All Statuses',
      allTypes: 'All Types',
      searchVehicles: 'Search Vehicles',
      status: 'Status',
      type: 'Type',
      carNumber: 'Car Number',
      vehicle: 'Vehicle',
      year: 'Year',
      color: 'Color',
      fuelType: 'Fuel Type',
      currentKm: 'Current Km',
      pricePerDay: 'Price Per Day',
      actions: 'Actions',
      noVehiclesFound: 'No vehicles found',
      vehicleDetails: 'Vehicle Details',
      noCustomersFound: 'No customers found',
      noBookingsFound: 'No bookings found',
      createNewBooking: 'Create New Booking',
      updateBookingDetails: 'Update Booking Details',
      enterBookingDetails: 'Enter Booking Details',
      totalPrice: 'Total Price',
      customer: 'Customer',
      startDate: 'Start Date',
      endDate: 'End Date',
      selectCustomer: 'Select Customer',
      selectStartDate: 'Select Start Date',
      selectEndDate: 'Select End Date',
      selectVehicle: 'Select Vehicle',
      selectDatesFirst: 'Select Dates First',
      noVehiclesAvailable: 'No vehicles available for the selected dates',
      startKm: 'Start Km Reading',
      cancel: 'Cancel',
      update: 'Update',
      createBooking: 'Create Booking',
      addNewCustomer: 'Add New Customer',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      passportNumber: 'Passport Number',
      visaNumber: 'Visa Number',
      address: 'Address',
      required: 'Required',
      enterValidEmail: 'Enter a valid email',
      addCustomer: 'Add Customer',
      returnKm: 'Return Km Reading',
      kmDriven: 'Km Driven',
      sedan: 'Sedan',
      suv: 'SUV',
      hatchback: 'Hatchback',
      luxury: 'Luxury',
      van: 'Van',
      petrol: 'Petrol',
      diesel: 'Diesel',
      electric: 'Electric',
      hybrid: 'Hybrid',
      available: 'Available',
      booked: 'Booked',
      maintenance: 'Maintenance',
      archived: 'Archived',
      pending: 'Pending',
      ongoing: 'Ongoing',
      completed: 'Completed',
      cancelled: 'Cancelled',
      new: 'New',
      returning: 'Returning',
      weekly: 'Weekly',
      monthly: 'Monthly',
      revenue: 'Revenue',
      day: 'Day',
      month: 'Month',
      perDay: '/day',
      currency: 'OMR',
      addNewVehicle: 'Add New Vehicle',
      editVehicle: 'Edit Vehicle',
      make: 'Make',
      model: 'Model',
      save: 'Save',
      customerId: 'Customer ID',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      passport: 'Passport',
      dateAdded: 'Date Added',
      bookingId: 'Booking ID',
      clearFilters: 'Clear Filters',
      newBooking: 'New Booking',
      completeBooking: 'Complete Booking',
      editBooking: 'Edit Booking',
      completeBookingConfirmation: 'Are you sure you want to complete this booking? You will need to enter the return km reading.',
      proceed: 'Proceed',
      complete: 'Complete',
      enterReturnKm: 'Enter return km reading to complete the booking',
      bookingUpdated: 'Booking Updated',
      bookingUpdatedDesc: 'Booking information has been updated successfully',
      bookingCreated: 'Booking Created',
      bookingCreatedDesc: 'A new booking has been created successfully',
      vehicleUpdated: 'Vehicle Updated',
      vehicleUpdatedDesc: 'Vehicle information has been updated successfully',
      vehicleArchived: 'Vehicle Archived',
      vehicleArchivedDesc: 'The vehicle has been removed from the active vehicles list',
      updateCustomer: 'Update Customer',
      customerUpdatedSuccess: 'Customer information has been updated successfully',
      customerAddedSuccess: 'A new customer has been added successfully',
      archivedVehiclesDesc: 'View archived vehicles',
      restore: 'Restore',
      accessDenied: 'Access Denied',
      onlyAdminCanArchiveVehicles: 'Only admins can archive vehicles',
      onlyAdminCanEditVehicles: 'Only admins can edit vehicles',
      onlyAdminCanManageVehicles: 'Only admins can manage vehicles',
      onlyAdminCanAccessArchivedVehicles: 'Only admins can access the archived vehicles page',
      cannotEditCompletedBooking: 'Cannot edit completed bookings. Please contact an admin.',
      passportAlreadyExists: 'Passport Already Exists',
      customerWithPassportExists: 'A customer with this passport number already exists',
      customerExists: 'Customer Exists',
      updatingExistingCustomer: 'Existing customer information will be updated',
      totalBookings: 'Total Bookings',
      completedBookings: 'Completed Bookings',
      loggedInAs: 'Logged in as',
      adminUser: 'Admin User',
      general: 'General',
      specifications: 'Specifications',
      images: 'Images',
      enterNewMake: 'Enter new make',
      enterNewModel: 'Enter new model',
      add: 'Add',
      noImage: 'No Image',
      view: 'View',
      edit: 'Edit'
    },
    ar: {
      dashboard: 'لوحة القيادة',
      vehicles: 'المركبات',
      bookings: 'الحجوزات',
      customers: 'العملاء',
      settings: 'الإعدادات',
      archivedVehicles: 'المركبات المؤرشفة',
      logout: 'تسجيل الخروج',
      language: 'اللغة',
      branch: 'الفرع',
      allBranches: 'جميع الفروع',
      totalActiveVehicles: 'إجمالي المركبات النشطة',
      availableVehicles: 'المركبات المتاحة',
      activeBookings: 'الحجوزات النشطة',
      totalRevenue: 'إجمالي الإيرادات',
      vehicleStatus: 'حالة المركبات',
      revenueOverview: 'نظرة عامة على الإيرادات',
      recentBookings: 'الحجوزات الأخيرة',
      allStatuses: 'جميع الحالات',
      allTypes: 'جميع الأنواع',
      searchVehicles: 'البحث عن مركبات',
      status: 'الحالة',
      type: 'النوع',
      carNumber: 'رقم السيارة',
      vehicle: 'المركبة',
      year: 'السنة',
      color: 'اللون',
      fuelType: 'نوع الوقود',
      currentKm: 'الكيلومترات الحالية',
      pricePerDay: 'السعر في اليوم',
      actions: 'الإجراءات',
      noVehiclesFound: 'لم يتم العثور على مركبات',
      vehicleDetails: 'تفاصيل المركبة',
      noCustomersFound: 'لم يتم العثور على عملاء',
      noBookingsFound: 'لم يتم العثور على حجوزات',
      createNewBooking: 'إنشاء حجز جديد',
      updateBookingDetails: 'تحديث تفاصيل الحجز',
      enterBookingDetails: 'أدخل تفاصيل الحجز',
      totalPrice: 'السعر الإجمالي',
      customer: 'العميل',
      startDate: 'تاريخ البدء',
      endDate: 'تاريخ الانتهاء',
      selectCustomer: 'اختر العميل',
      selectStartDate: 'اختر تاريخ البدء',
      selectEndDate: 'اختر تاريخ الانتهاء',
      selectVehicle: 'اختر المركبة',
      selectDatesFirst: 'اختر التواريخ أولاً',
      noVehiclesAvailable: 'لا توجد مركبات متاحة للتواريخ المحددة',
      startKm: 'قراءة عداد البدء',
      cancel: 'إلغاء',
      update: 'تحديث',
      createBooking: 'إنشاء حجز',
      addNewCustomer: 'إضافة عميل جديد',
      fullName: 'الاسم الكامل',
      emailAddress: 'البريد الإلكتروني',
      phoneNumber: 'رقم الهاتف',
      passportNumber: 'رقم جواز السفر',
      visaNumber: 'رقم التأشيرة',
      address: 'العنوان',
      required: 'مطلوب',
      enterValidEmail: 'أدخل بريد إلكتروني صالح',
      addCustomer: 'إضافة عميل',
      returnKm: 'قراءة العداد عند العودة',
      kmDriven: 'الكيلومترات المقطوعة',
      sedan: 'سيدان',
      suv: 'دفع رباعي',
      hatchback: 'هاتشباك',
      luxury: 'فاخرة',
      van: 'شاحنة صغيرة',
      petrol: 'بنزين',
      diesel: 'ديزل',
      electric: 'كهربائي',
      hybrid: 'هجين',
      available: 'متاح',
      booked: 'محجوز',
      maintenance: 'صيانة',
      archived: 'مؤرشف',
      pending: 'قيد الانتظار',
      ongoing: 'جارٍ',
      completed: 'مكتمل',
      cancelled: 'ملغي',
      new: 'جديد',
      returning: 'عائد',
      weekly: 'أسبوعي',
      monthly: 'شهري',
      revenue: 'الإيرادات',
      day: 'اليوم',
      month: 'الشهر',
      perDay: '/يوم',
      currency: 'ر.ع',
      addNewVehicle: 'إضافة مركبة جديدة',
      editVehicle: 'تحرير المركبة',
      make: 'الصنع',
      model: 'الموديل',
      save: 'حفظ',
      customerId: 'معرف العميل',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      passport: 'جواز السفر',
      dateAdded: 'تاريخ الإضافة',
      bookingId: 'معرف الحجز',
      clearFilters: 'مسح الفلاتر',
      newBooking: 'حجز جديد',
      completeBooking: 'إكمال الحجز',
      editBooking: 'تحرير الحجز',
      completeBookingConfirmation: 'هل أنت متأكد من أنك تريد إكمال هذا الحجز؟ ستحتاج إلى إدخال قراءة العداد عند العودة.',
      proceed: 'متابعة',
      complete: 'إكمال',
      enterReturnKm: 'أدخل قراءة العداد عند العودة لإكمال الحجز',
      bookingUpdated: 'تم تحديث الحجز',
      bookingUpdatedDesc: 'تم تحديث معلومات الحجز بنجاح',
      bookingCreated: 'تم إنشاء الحجز',
      bookingCreatedDesc: 'تم إنشاء حجز جديد بنجاح',
      vehicleUpdated: 'تم تحديث المركبة',
      vehicleUpdatedDesc: 'تم تحديث معلومات المركبة بنجاح',
      vehicleArchived: 'تمت أرشفة المركبة',
      vehicleArchivedDesc: 'تمت إزالة المركبة من قائمة المركبات النشطة',
      updateCustomer: 'تم تحديث العميل',
      customerUpdatedSuccess: 'تم تحديث معلومات العميل بنجاح',
      customerAddedSuccess: 'تمت إضافة عميل جديد بنجاح',
      archivedVehiclesDesc: 'عرض المركبات المؤرشفة',
      restore: 'استعادة',
      accessDenied: 'تم رفض الوصول',
      onlyAdminCanArchiveVehicles: 'يمكن للمسؤولين فقط أرشفة المركبات',
      onlyAdminCanEditVehicles: 'يمكن للمسؤولين فقط تحرير المركبات',
      onlyAdminCanManageVehicles: 'يمكن للمسؤولين فقط إدارة المركبات',
      onlyAdminCanAccessArchivedVehicles: 'يمكن للمسؤولين فقط الوصول إلى صفحة المركبات المؤرشفة',
      cannotEditCompletedBooking: 'لا يمكن تحرير الحجوزات المكتملة. يرجى الاتصال بالمسؤول.',
      passportAlreadyExists: 'جواز سفر موجود',
      customerWithPassportExists: 'يوجد بالفعل عميل بهذا الرقم الجواز',
      customerExists: 'العميل موجود',
      updatingExistingCustomer: 'سيتم تحديث معلومات العميل الموجود',
      totalBookings: 'إجمالي الحجوزات',
      completedBookings: 'الحجوزات المكتملة',
      loggedInAs: 'تم تسجيل الدخول باسم',
      adminUser: 'المستخدم المسؤول',
      general: 'عام',
      specifications: 'المواصفات',
      images: 'الصور',
      enterNewMake: 'أدخل صانع جديد',
      enterNewModel: 'أدخل موديل جديد',
      add: 'إضافة',
      noImage: 'لا توجد صورة',
      view: 'عرض',
      edit: 'تحرير'
    }
  };

  const t = (key: string) => {
    return translations[language as keyof typeof translations]?.[key] || key;
  };

  const value: LanguageContextProps = {
    language,
    setLanguage,
    toggleLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
